// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtldrvtwmoevryvypcsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0bGRydnR3bW9ldnJ5dnlwY3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzU4NTYsImV4cCI6MjA2MTAxMTg1Nn0.U-klaWZ7DCEpqrBMcTebWrdr8CeEVrAs6Ubc3Hqh4sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);